### ISSUE TITLE
Config map is not created on OSO

### ISSUE THREAD

**Issue by ghost** [openshift-vertx-examples/vertx-configmap-example#12]
Steps to reproduce:

1. Login to OSIO.
2. Create a space and add a codebase from quickstarts - Vertx with Config map
3. Wait until stage deployment is completed.

```
io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: GET at: https://172.30.0.1/api/v1/namespaces/yivantso-stage/configmaps/app-config. Message: Forbidden!Configured service account doesn't have access. Service account may have been revoked..
```

This is because app-config map is never created. As a result, the app is broken

**Comment by cescoffier** [comment]
As indicated in the doc, you need to give the "read" permission on your project:
```
oc policy add-role-to-user view -n $(oc project -q) -z default
```

Also, ensure that you have created the config map explicitly:

```
oc create configmap app-config --from-file=app-config.yml
```

Check https://appdev.openshift.io/docs/vertx-runtime.html#mission-configmap-vertx to get more details.
