### ISSUE TITLE
License names mismatch

### ISSUE THREAD

**Issue by spisiakm** [openshift-vertx-examples/vertx-configmap-example#7]
Hi,
there's same problem with license names as in HTTP booster, see openshiftio-vertx-boosters/vertx-http-booster#14 .

**Comment by cescoffier** [comment]
@spisiakm can you recheck and close the issue if we are fine?

**Comment by spisiakm** [comment]
@cescoffier I'm going to close all the license-related issues in the boosters as they should be resolved by now.
